version: '2'
services:
  lagrangian:
    network_mode: host
    restart: always
    build: ./lagrangian
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - serverfiles:/usr/srv/serverfiles
      - servertemp:/servertemp
    ports:
      - '25565:25565/udp'
      - '25565:25565/tcp'
      - '25575:25575/udp'
      - '25575:25575/tcp'
  scp:
    network_mode: host
    restart: always
    build: ./scp
    privileged: false
    labels:
      io.balena.features.dbus: 1
    volumes:
      - serverfiles:/serverfiles
      - servertemp:/servertemp
    ports:
      - '22:22/udp'
      - '22:22/tcp'
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  rcon:
    network_mode: host
    restart: always
    build: ./rcon
    privileged: true
    ports:
      - '25575:25575/udp'
      - '25575:25575/tcp'
volumes:
  serverfiles:
  servertemp:
